config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "main#index"
  get "about", to: "main#about"
  get "contact", to: "main#contact"
  get "services", to: redirect('/404')
  get "services/hardware", to: "services#hardware"
  get "services/support", to: "services#support"
  get "services/network", to: "services#network"
  get "services/IPphone", to: "services#IPphone"
  get "services/cloud", to: "services#cloud"
  get "services/security", to: "services#security"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, legth: { min: 3, max: 50 }
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end

    def about
    end

    def contact
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    def hardware
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body> 
<div class="spinner">
  <div class="spinner-logo-wrap">
    <%= image_tag "logo.png", :class => "spinner-img"%>
  </div>       
</div>
<header>
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "Hardware & Software", services_hardware_path %></li>
  <li><%= link_to "IT Support Services", services_support_path %></li>
  <li><%= link_to "Network Services", services_network_path %></li>
  <li><%= link_to "IP Phone Services", services_IPphone_path %></li>
  <li><%= link_to "Cloud Solutions & Services", services_cloud_path %></li>  
  <li><%= link_to "Cyber Security Services", services_security_path %></li>  
</ul>

<nav>
<div class="container">
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">
      <%= image_tag "logo.png", :class => "navbar-logo" %>     
    </a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Home", root_path %></li>
      <li><a href="/about">About us</a></li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-trigger" data-target="dropdown1">Services<i class="material-icons right">arrow_drop_down</i></a></li>
      <li><a href="/contact">Contact</a></li>
    </ul>
  </div>
</div>
</nav>
</header>

<main>
  <%= yield %>
</main>

<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="footer-wrap">
          <div class="footer-wrap_logo">
            <%= image_tag "logo.png", :class => "footer-logo" %>
          </div>
          <div class="footer-wrap_socials">
            <p>Social media</p>
            <%= image_tag "facebook.svg" %>                        
            <%= image_tag "instagram.svg" %>
          </div>   
      
          <div class="footer-wrap_logo">
            <p>Services</p>
            <ul>
              <li>
                Hardware & Software
              </li>
              <li>
                IT Support Services
              </li>
              <li>
                Network Services
              </li>
              <li>
                IP Phone Services
              </li>
              <li>
                Cloud Solutions & Services
              </li>
              <li>
                Cyber Security Services
              </li>                          
            </ul>
          </div>
          <div class="footer-wrap_socials">
            <p>Contact</p>
            <ul>
              <li>
                Yo
              </li>
              <li>
                Sup
              </li>
              <li>
                Bruh
              </li>
            </ul>        
          </div>   
      </div>
    </div>
  </div>
    <div class="footer-copyright">
      <div class="container">
            © 2019
      <a class="grey-text text-lighten-4 right" href="#!">Tikken</a>
    </div>
  </div>
</footer>

  </body>
</html>

app/views/main/about.slim
h1 Yo I'm an about page

app/views/main/contact.slim
h1 Call your mama to contact me

app/views/main/index.slim
div class="hero-image-text"
  h2 We will help make your business more successful

div class="call-to-action"
  button class="btn btn-waves" Contact

= image_tag "hero.png", :class => "hero"

div class="text1 container"
  h5 We recognize how hard it is for you to set up, implement or fix the technological problems (that have arisen). We are ready to help you forget your worries and save the time you spend managing your IT infrastructure and network. ShorIT provides full support for the IT spectrum needed for your business. From email issues to repairing parts of your PC.

div class="services center"
  div class="services-title"
  h2 Our Services
  div class="services-items-container"
    div class="services-item"
      = image_tag "1.png", :class => "hero" 
      h6 Hardware & Software
    div class="services-item"
      = image_tag "2.png", :class => "hero" 
      h6 IT Support Services
    div class="services-item"
      = image_tag "3.png", :class => "hero" 
      h6 Network Services
      
  div class="services-items-container2"    
    div class="services-item"
      = image_tag "4.png", :class => "hero" 
      h6 IP Phone Services
    div class="services-item"
      = image_tag "5.png", :class => "hero"     
      h6 Cloud Solutions & Services  
    div class="services-item"
      = image_tag "6.png", :class => "hero" 
      h6 Cyber Security Services

div class="text2 container"
  h5 We’ll help you solve your technological problems that you have to face on a daily basis. We provide flexible, professional IT support and reliable services for your business, providing everything you need to efficient, safe and reliable use of your IT environment.

div class="sertificates center"
  h2 Sertificates
  div class="sertificates-items"
    = image_tag "sertificate1.png", :class => "materialboxed", width: "200"
    = image_tag "sertificate2.png", :class => "materialboxed", width: "200"
    = image_tag "sertificate3.png", :class => "materialboxed", width: "200"
    = image_tag "sertificate4.png", :class => "materialboxed", width: "200"

app/views/services/hardware.slim
h2 You I'm a hardware